/var/log/x-ui/access.log {
    daily
    maxsize 64M
    rotate 64
    maxage 7
    missingok
    notifempty
    compress
    delaycompress
    create 0600 root root
    su root root
    sharedscripts
    postrotate
        /usr/bin/python3 /opt/xray-audit/reopen_logger.py
    endscript
}
