#!/usr/bin/env bash
set -u

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

fail() {
    echo "xui-qos rollback: $*" >&2
    exit 1
}

backup_dir=${1:-}
[[ -n "$backup_dir" ]] || fail "backup directory is required"
case "$backup_dir" in
    /var/backups/xui-qos/install-*|/var/backups/xui-qos/uninstall-*) ;;
    *) fail "refusing unexpected backup path" ;;
esac
[[ -d "$backup_dir" && ! -L "$backup_dir" ]] || fail "backup directory is invalid"
[[ $(stat -c '%U' "$backup_dir") == root ]] || fail "backup directory is not root-owned"
[[ -r "$backup_dir/state.env" ]] || fail "backup state is missing"

# state.env is generated by the root-only installer in a mode-0700 directory.
# shellcheck disable=SC1090
. "$backup_dir/state.env"

project_paths=(
    /etc/default/x-ui
    /etc/default/xray-qos
    /etc/modules-load.d/xui-qos.conf
    /etc/nginx/conf.d/xui-qos.conf
    /etc/sysctl.d/99-xui-qos-bbr.conf
    /etc/systemd/system/xray-qos.service
    /etc/systemd/system/xray-qos-control.service
    /etc/systemd/system/xray-qos-web.service
    /etc/xray-qos
    /etc/xray-qos-web
    /opt/xray-qos-web
    /usr/local/sbin/xray-qos
    /usr/local/sbin/xui-qos-rollback-install
    /usr/local/sbin/xui-qos-uninstall
    /usr/local/sbin/xui-qos-verify
)

restore_path() {
    local target=$1 relative=${1#/} saved="$backup_dir/present/${1#/}"
    if [[ -e "$saved" || -L "$saved" ]]; then
        rm -rf -- "$target"
        mkdir -p -- "$(dirname -- "$target")"
        cp -a -- "$saved" "$target"
    elif [[ -e "$backup_dir/absent/$relative" ]]; then
        rm -rf -- "$target"
    else
        echo "xui-qos rollback: missing backup marker for $target" >&2
        return 1
    fi
}

systemctl stop xray-qos-web.service xray-qos-control.service 2>/dev/null || true
if [[ -x /usr/local/sbin/xray-qos ]]; then
    /usr/local/sbin/xray-qos cleanup >/dev/null 2>&1 || true
fi
systemctl stop xray-qos.service 2>/dev/null || true
systemctl stop nginx.service x-ui.service 2>/dev/null || true
systemctl disable xray-qos-web.service xray-qos-control.service xray-qos.service >/dev/null 2>&1 || true

rollback_errors=0
for project_path in "${project_paths[@]}"; do
    restore_path "$project_path" || rollback_errors=1
done

if [[ -s "$backup_dir/x-ui.db" ]]; then
    install -o root -g root -m "${XUI_DB_MODE:-600}" "$backup_dir/x-ui.db" /etc/x-ui/x-ui.db || rollback_errors=1
fi

systemctl daemon-reload
sysctl --system >/dev/null 2>&1 || true
if [[ -n "${ORIGINAL_DEFAULT_QDISC:-}" ]]; then
    sysctl -q -w "net.core.default_qdisc=${ORIGINAL_DEFAULT_QDISC}" || true
fi
if [[ -n "${ORIGINAL_TCP_CC:-}" ]]; then
    sysctl -q -w "net.ipv4.tcp_congestion_control=${ORIGINAL_TCP_CC}" || true
fi

case "${ORIGINAL_ROOT_QDISC:-}" in
    fq|fq_codel)
        tc qdisc replace dev "${WAN_INTERFACE:?}" root "${ORIGINAL_ROOT_QDISC}" >/dev/null 2>&1 || true
        ;;
esac

if [[ "${QOS_WAS_ENABLED:-no}" == yes ]]; then
    systemctl enable xray-qos.service >/dev/null 2>&1 || true
fi
if [[ "${CONTROL_WAS_ENABLED:-no}" == yes ]]; then
    systemctl enable xray-qos-control.service >/dev/null 2>&1 || true
fi
if [[ "${WEB_WAS_ENABLED:-no}" == yes ]]; then
    systemctl enable xray-qos-web.service >/dev/null 2>&1 || true
fi
if [[ "${XUI_WAS_ACTIVE:-yes}" == yes ]]; then
    systemctl start x-ui.service || rollback_errors=1
fi
if [[ "${NGINX_WAS_ACTIVE:-no}" == yes ]]; then
    nginx -t && systemctl start nginx.service || rollback_errors=1
fi
if [[ "${QOS_WAS_ACTIVE:-no}" == yes ]]; then
    systemctl start xray-qos.service || rollback_errors=1
fi
if [[ "${CONTROL_WAS_ACTIVE:-no}" == yes ]]; then
    systemctl start xray-qos-control.service || rollback_errors=1
fi
if [[ "${WEB_WAS_ACTIVE:-no}" == yes ]]; then
    systemctl start xray-qos-web.service || rollback_errors=1
fi
if [[ "${PTR_WAS_ENABLED:-no}" == yes ]]; then
    systemctl enable xray-audit-ptr.socket >/dev/null 2>&1 || true
fi
if [[ "${PTR_WAS_ACTIVE:-no}" == yes ]]; then
    systemctl start xray-audit-ptr.socket || rollback_errors=1
fi

if (( rollback_errors != 0 )); then
    fail "rollback completed with errors; inspect systemd status"
fi
echo "xui-qos rollback: restored $backup_dir"
