#!/usr/bin/env bash
set -Eeuo pipefail

umask 077
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RESULT_FILE=/etc/xray-qos-web/install-result.env

uninstall_backup=
rollback_unit=
rollback_armed=no
backup_ready=no
finished=no

die() {
    echo "xui-qos uninstall: $*" >&2
    exit 1
}

is_uint() {
    [[ $1 =~ ^[0-9]+$ ]]
}

service_active() {
    systemctl is-active --quiet "$1" && echo yes || echo no
}

service_enabled() {
    systemctl is-enabled --quiet "$1" 2>/dev/null && echo yes || echo no
}

cleanup() {
    local rc=$?
    trap - EXIT INT TERM
    if (( rc != 0 )) && [[ "$backup_ready" == yes && "$finished" != yes ]]; then
        echo "xui-qos uninstall: operation failed; restoring the integrated state" >&2
        if [[ "$rollback_armed" == yes ]]; then
            systemctl stop "${rollback_unit}.timer" >/dev/null 2>&1 || true
        fi
        "$uninstall_backup/rollback.sh" "$uninstall_backup" || \
            echo "xui-qos uninstall: automatic rollback reported an error; backup: $uninstall_backup" >&2
    fi
    exit "$rc"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

[[ $(id -u) -eq 0 ]] || die "run as root"
[[ -f "$RESULT_FILE" && ! -L "$RESULT_FILE" ]] || die "$RESULT_FILE is missing or unsafe"
[[ $(stat -c '%U' "$RESULT_FILE") == root ]] || die "$RESULT_FILE must be root-owned"
result_mode=$(stat -c '%a' "$RESULT_FILE")
(( (8#$result_mode & 022) == 0 )) || die "$RESULT_FILE is writable by group or others"
[[ -x /usr/local/sbin/xui-qos-rollback-install ]] || die "rollback helper is missing"

exec 9>/run/lock/xui-qos-install.lock
flock -n 9 || die "another xui-qos installation or uninstall is running"

# This file is generated by the root-only installer and is mode 0600.
# shellcheck disable=SC1090
. "$RESULT_FILE"

case "${XUI_QOS_PREVIOUS_PORT_PRESENT:-}" in
    yes)
        is_uint "${XUI_QOS_PREVIOUS_PORT:-}" && \
            (( XUI_QOS_PREVIOUS_PORT >= 1 && XUI_QOS_PREVIOUS_PORT <= 65535 )) \
            || die "invalid saved 3x-ui port"
        direct_port=$XUI_QOS_PREVIOUS_PORT
        ;;
    no)
        is_uint "${XUI_QOS_PANEL_PORT:-}" && \
            (( XUI_QOS_PANEL_PORT >= 1 && XUI_QOS_PANEL_PORT <= 65535 )) \
            || die "invalid saved panel port"
        direct_port=$XUI_QOS_PANEL_PORT
        ;;
    *) die "invalid saved previous-port flag" ;;
esac
case "${XUI_QOS_PUBLIC_SCHEME:-}" in
    http|https) ;;
    *) die "invalid saved panel scheme" ;;
esac
[[ ${XUI_QOS_BASE_PATH:-} == /*/ && ${XUI_QOS_BASE_PATH:-} != *..* && \
   ${XUI_QOS_BASE_PATH:-} =~ ^/[A-Za-z0-9_/-]*/$ ]] || die "invalid saved panel path"
[[ ${XUI_QOS_WAN:-} =~ ^[A-Za-z0-9_.:-]{1,15}$ ]] || die "invalid saved WAN interface"
case "${XUI_QOS_ORIGINAL_ROOT_QDISC:-}" in
    fq|fq_codel|noqueue) ;;
    *) die "invalid saved original root qdisc" ;;
esac
case "${XUI_QOS_PUBLIC_AUTHORITY:-}" in
    *$'\n'*|*$'\r'*|'') die "invalid saved panel authority" ;;
esac
python3 - "${XUI_QOS_PREVIOUS_WEB_LISTEN:-}" <<'PY'
import ipaddress, sys
value = sys.argv[1].strip()
if value in {'', '*', 'localhost', '0.0.0.0', '::', '[::]'}:
    raise SystemExit(0)
try:
    ipaddress.ip_address(value.strip('[]'))
except ValueError as exc:
    raise SystemExit('invalid saved 3x-ui listen address') from exc
PY

uninstall_backup="/var/backups/xui-qos/uninstall-$(date -u +%Y%m%dT%H%M%SZ)-$$"
install -d -m 0700 -o root -g root "$uninstall_backup/present" "$uninstall_backup/absent"

project_paths=(
    /etc/default/x-ui
    /etc/default/xray-qos
    /etc/modules-load.d/xui-qos.conf
    /etc/nginx/conf.d/xui-qos.conf
    /etc/sysctl.d/99-xui-qos-bbr.conf
    /etc/systemd/system/xray-qos.service
    /etc/systemd/system/xray-qos-control.service
    /etc/systemd/system/xray-qos-web.service
    /etc/xray-qos
    /etc/xray-qos-web
    /opt/xray-qos-web
    /usr/local/sbin/xray-qos
    /usr/local/sbin/xui-qos-rollback-install
    /usr/local/sbin/xui-qos-uninstall
    /usr/local/sbin/xui-qos-verify
)

backup_item() {
    local target=$1 relative=${1#/}
    if [[ -e "$target" || -L "$target" ]]; then
        mkdir -p -- "$uninstall_backup/present/$(dirname -- "$relative")"
        cp -a -- "$target" "$uninstall_backup/present/$relative"
    else
        mkdir -p -- "$uninstall_backup/absent/$(dirname -- "$relative")"
        : >"$uninstall_backup/absent/$relative"
    fi
}

for project_path in "${project_paths[@]}"; do
    backup_item "$project_path"
done

[[ -f /etc/x-ui/x-ui.db && ! -L /etc/x-ui/x-ui.db ]] || die "3x-ui database is missing or unsafe"
xui_db_mode=$(stat -c '%a' /etc/x-ui/x-ui.db)
python3 - "$uninstall_backup/x-ui.db" <<'PY'
import sqlite3, sys
source = sqlite3.connect('/etc/x-ui/x-ui.db')
target = sqlite3.connect(sys.argv[1])
try:
    source.backup(target)
finally:
    target.close(); source.close()
PY
chmod "$xui_db_mode" "$uninstall_backup/x-ui.db"

current_root_qdisc=$(tc -j qdisc show dev "$XUI_QOS_WAN" | python3 -c '
import json,sys
items=json.load(sys.stdin)
root=next((item for item in items if item.get("root") is True), None)
print((root or {}).get("kind", "noqueue"))
')

qos_was_active=$(service_active xray-qos.service)
control_was_active=$(service_active xray-qos-control.service)
web_was_active=$(service_active xray-qos-web.service)
nginx_was_active=$(service_active nginx.service)
xui_was_active=$(service_active x-ui.service)
qos_was_enabled=$(service_enabled xray-qos.service)
control_was_enabled=$(service_enabled xray-qos-control.service)
web_was_enabled=$(service_enabled xray-qos-web.service)
ptr_was_active=$(service_active xray-audit-ptr.socket)
ptr_was_enabled=$(service_enabled xray-audit-ptr.socket)

{
    printf 'WAN_INTERFACE=%q\n' "$XUI_QOS_WAN"
    printf 'ORIGINAL_ROOT_QDISC=%q\n' "$current_root_qdisc"
    printf 'XUI_DB_MODE=%q\n' "$xui_db_mode"
    printf 'ORIGINAL_TCP_CC=%q\n' "$(sysctl -n net.ipv4.tcp_congestion_control)"
    printf 'ORIGINAL_DEFAULT_QDISC=%q\n' "$(sysctl -n net.core.default_qdisc)"
    printf 'QOS_WAS_ACTIVE=%q\n' "$qos_was_active"
    printf 'CONTROL_WAS_ACTIVE=%q\n' "$control_was_active"
    printf 'WEB_WAS_ACTIVE=%q\n' "$web_was_active"
    printf 'NGINX_WAS_ACTIVE=%q\n' "$nginx_was_active"
    printf 'XUI_WAS_ACTIVE=%q\n' "$xui_was_active"
    printf 'QOS_WAS_ENABLED=%q\n' "$qos_was_enabled"
    printf 'CONTROL_WAS_ENABLED=%q\n' "$control_was_enabled"
    printf 'WEB_WAS_ENABLED=%q\n' "$web_was_enabled"
    printf 'PTR_WAS_ACTIVE=%q\n' "$ptr_was_active"
    printf 'PTR_WAS_ENABLED=%q\n' "$ptr_was_enabled"
} >"$uninstall_backup/state.env"
install -o root -g root -m 0700 /usr/local/sbin/xui-qos-rollback-install "$uninstall_backup/rollback.sh"

rollback_unit="xui-qos-uninstall-rollback-$(date -u +%Y%m%d%H%M%S)-$$"
systemd-run --quiet --unit="$rollback_unit" --on-active=5m --timer-property=AccuracySec=1s \
    "$uninstall_backup/rollback.sh" "$uninstall_backup"
rollback_armed=yes
backup_ready=yes

systemctl stop xray-qos-web.service xray-qos-control.service
if [[ -f /etc/systemd/system/xray-audit-ptr.socket ]]; then
    systemctl stop xray-audit-ptr.socket
    systemctl disable xray-audit-ptr.socket >/dev/null
fi
/usr/local/sbin/xray-qos cleanup
systemctl stop xray-qos.service
systemctl disable xray-qos-web.service xray-qos-control.service xray-qos.service >/dev/null

systemctl stop nginx.service x-ui.service
rm -f -- /etc/nginx/conf.d/xui-qos.conf

python3 - "$XUI_QOS_PREVIOUS_PORT_PRESENT" "${XUI_QOS_PREVIOUS_PORT:-}" <<'PY'
from pathlib import Path
import os, sys, tempfile

path = Path('/etc/default/x-ui')
present = sys.argv[1] == 'yes'
previous = sys.argv[2]
lines = path.read_text(encoding='utf-8').splitlines() if path.exists() else []
result = []
replaced = False
for line in lines:
    if line.startswith('XUI_PORT='):
        if present and not replaced:
            result.append(f'XUI_PORT={previous}')
            replaced = True
        continue
    result.append(line)
if present and not replaced:
    result.append(f'XUI_PORT={previous}')
if result:
    fd, name = tempfile.mkstemp(prefix='.x-ui.', dir=path.parent)
    with os.fdopen(fd, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(result) + '\n')
        handle.flush(); os.fsync(handle.fileno())
    os.chmod(name, 0o644)
    os.replace(name, path)
else:
    path.unlink(missing_ok=True)
PY

restore_listen=${XUI_QOS_PREVIOUS_WEB_LISTEN:-0.0.0.0}
[[ -n "$restore_listen" ]] || restore_listen=0.0.0.0
/usr/local/x-ui/x-ui setting -listenIP "$restore_listen" >/dev/null

direct_connect_host=$(python3 - "$restore_listen" <<'PY'
import ipaddress, sys
value = sys.argv[1].strip()
if value in {'', '*', 'localhost', '0.0.0.0'}:
    print('127.0.0.1')
elif value in {'::', '[::]'}:
    print('[::1]')
else:
    address = ipaddress.ip_address(value.strip('[]'))
    print(f'[{address}]' if address.version == 6 else address)
PY
)

case "$XUI_QOS_ORIGINAL_ROOT_QDISC" in
    fq|fq_codel)
        tc qdisc replace dev "$XUI_QOS_WAN" root "$XUI_QOS_ORIGINAL_ROOT_QDISC"
        ;;
    noqueue)
        tc qdisc del dev "$XUI_QOS_WAN" root 2>/dev/null || true
        ;;
esac

systemctl daemon-reload
systemctl start x-ui.service

direct_ready=no
for _attempt in $(seq 1 30); do
    direct_code=$(curl --noproxy '*' -ksS -H "Host: ${XUI_QOS_PUBLIC_AUTHORITY}" -o /dev/null -w '%{http_code}' \
        "${XUI_QOS_PUBLIC_SCHEME}://${direct_connect_host}:${direct_port}${XUI_QOS_BASE_PATH}" || true)
    case "$direct_code" in
        2??|3??) direct_ready=yes; break ;;
    esac
    sleep 1
done
[[ "$direct_ready" == yes ]] || die "3x-ui did not become reachable in its original listening mode"

nginx -t
systemctl start nginx.service

rm -rf -- /opt/xray-qos-web /etc/xray-qos-web
# Independent audit continues running: never remove its selected sending time.
rm -f -- /etc/xray-qos/nodes.json
rmdir -- /etc/xray-qos 2>/dev/null || true
rm -f -- /etc/default/xray-qos \
    /etc/systemd/system/xray-qos.service \
    /etc/systemd/system/xray-qos-control.service \
    /etc/systemd/system/xray-qos-web.service \
    /usr/local/sbin/xray-qos \
    /usr/local/sbin/xui-qos-rollback-install \
    /usr/local/sbin/xui-qos-verify \
    /usr/local/sbin/xui-qos-uninstall
systemctl daemon-reload

systemctl is-active --quiet x-ui.service || die "x-ui.service is not active after uninstall"
systemctl is-active --quiet nginx.service || die "nginx.service is not active after uninstall"

systemctl stop "${rollback_unit}.timer" >/dev/null
rollback_armed=no
finished=yes

echo "xui-qos uninstall: removed; original 3x-ui listening mode restored"
echo "rollback backup: $uninstall_backup"
echo "Node notes in /var/lib/xray-qos-web are preserved."
if [[ -f /opt/xray-audit/.managed-by-codex-audit ]]; then
    echo "The separate audit add-on remains installed (including retention and scheduled mail). See docs/AUDIT.md to stop collection safely."
fi
