#!/usr/bin/env bash
set -Eeuo pipefail

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RESULT_FILE=/etc/xray-qos-web/install-result.env

die() {
    echo "xui-qos verify: $*" >&2
    exit 1
}

[[ $(id -u) -eq 0 ]] || die "run as root"
[[ -r "$RESULT_FILE" ]] || die "$RESULT_FILE is missing"
# This file is generated by the root-only installer and is mode 0600.
# shellcheck disable=SC1090
. "$RESULT_FILE"

nginx -t >/dev/null
for service in x-ui.service nginx.service xray-qos.service xray-qos-control.service xray-qos-web.service; do
    systemctl is-active --quiet "$service" || die "$service is not active"
done

[[ $(sysctl -n net.ipv4.tcp_congestion_control) == bbr || "${XUI_QOS_BBR_ENABLED:-no}" == no ]] \
    || die "BBR is not active"

upstream_socket=$(ss -H -ltnp "sport = :${XUI_QOS_UPSTREAM_PORT}" || true)
backend_socket=$(ss -H -ltnp "sport = :${XUI_QOS_BACKEND_PORT}" || true)
[[ "$upstream_socket" == *"127.0.0.1:${XUI_QOS_UPSTREAM_PORT}"* ]] || die "x-ui upstream is not loopback-only"
[[ "$backend_socket" == *"127.0.0.1:${XUI_QOS_BACKEND_PORT}"* ]] || die "QoS web backend is not loopback-only"

local_origin="${XUI_QOS_PUBLIC_SCHEME}://127.0.0.1:${XUI_QOS_PANEL_PORT}"
panel_file=$(mktemp)
trap 'rm -f -- "$panel_file"' EXIT
panel_code=$(curl -ksS -H "Host: ${XUI_QOS_PUBLIC_AUTHORITY}" -o "$panel_file" -w '%{http_code}' \
    "${local_origin}${XUI_QOS_BASE_PATH}")
[[ "$panel_code" == 200 ]] || die "panel returned HTTP $panel_code"
grep -q 'xui-qos-integration.js' "$panel_file" || die "integration script was not injected"

asset_code=$(curl -ksS -H "Host: ${XUI_QOS_PUBLIC_AUTHORITY}" -o /dev/null -w '%{http_code}' \
    "${local_origin}${XUI_QOS_BASE_PATH}xui-qos-integration.js")
[[ "$asset_code" == 200 ]] || die "integration asset returned HTTP $asset_code"

embed_code=$(curl -ksS -H "Host: ${XUI_QOS_PUBLIC_AUTHORITY}" -o /dev/null -w '%{http_code}' \
    "${local_origin}${XUI_QOS_BASE_PATH}qos-speed/")
[[ "$embed_code" == 401 || "$embed_code" == 403 ]] || die "unauthenticated dashboard returned HTTP $embed_code"

/usr/local/sbin/xray-qos status-json >/dev/null
/usr/sbin/runuser -u xray-qos-web -- /usr/bin/python3 /opt/xray-qos-web/healthcheck.py >/dev/null

echo "xui-qos verify: OK"
echo "panel: ${XUI_QOS_PANEL_URL}"
